<a href="https://colab.research.google.com/github/usman1911/DSA-Python/blob/main/DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q-Learning Demonstration in Python
# Problem statement:
# - Agent moves in a grid
# - Goal state gives reward
# - Some states are blocked/negative

import numpy as np
import random

# ENVIRONMENT SETUP

GRID_SIZE = 4
ACTIONS = ['up', 'down', 'left', 'right']

# Rewards
GOAL = (3, 3)
BLOCKED = [(1, 1), (2, 1)]   # blocked states
TRAP = (3, 1)                # negative reward state

# Q-table: rows = states, cols = actions
q_table = np.zeros((GRID_SIZE * GRID_SIZE, len(ACTIONS)))

# Hyperparameters
alpha = 0.1      # learning rate
gamma = 0.9      # discount factor
epsilon = 0.2    # exploration rate
episodes = 500


def state_to_index(state):
    return state[0] * GRID_SIZE + state[1]


def get_next_state(state, action):
    x, y = state

    if action == 0:   # up
        x = max(0, x - 1)
    elif action == 1: # down
        x = min(GRID_SIZE - 1, x + 1)
    elif action == 2: # left
        y = max(0, y - 1)
    elif action == 3: # right
        y = min(GRID_SIZE - 1, y + 1)

    # If blocked, stay in same state
    if (x, y) in BLOCKED:
        return state

    return (x, y)


def get_reward(state):
    if state == GOAL:
        return 100
    elif state == TRAP:
        return -100
    else:
        return -1

# TRAINING
for episode in range(episodes):
    state = (0, 0)  # start position

    while state != GOAL:
        state_idx = state_to_index(state)

        # Epsilon-greedy action selection
        if random.uniform(0, 1) < epsilon:
            action = random.randint(0, 3)
        else:
            action = np.argmax(q_table[state_idx])

        next_state = get_next_state(state, action)
        reward = get_reward(next_state)

        next_state_idx = state_to_index(next_state)

        # Q-learning update rule
        q_table[state_idx, action] = q_table[state_idx, action] + alpha * (
            reward + gamma * np.max(q_table[next_state_idx]) - q_table[state_idx, action]
        )

        # Stop if trap reached
        if next_state == TRAP:
            break

        state = next_state

# OUTPUT RESULTS
print("Learned Q-Table:\n")
print(np.round(q_table, 2))

print("\nOptimal path from start to goal:")
state = (0, 0)
path = [state]

while state != GOAL:
    state_idx = state_to_index(state)
    action = np.argmax(q_table[state_idx])
    next_state = get_next_state(state, action)

    if next_state == state:  # avoid infinite loop
        break

    path.append(next_state)
    state = next_state

print(path)

# Expected learned path example:
# [(0,0), (0,1), (0,2), (1,2), (2,2), (3,2), (3,3)]

Learned Q-Table:

[[ 43.63  33.86  47.05  54.95]
 [ 50.39  50.58  43.27  62.17]
 [ 60.7   63.18  51.54  70.19]
 [ 66.31  79.1   60.23  66.88]
 [ 46.15  -1.87   5.15   5.01]
 [  0.     0.     0.     0.  ]
 [ 11.55  78.74  18.03   7.67]
 [ 58.38  89.    61.31  74.8 ]
 [  2.44  -1.82  -1.82  -1.81]
 [  0.     0.     0.     0.  ]
 [ 13.15   2.11  37.06  88.99]
 [ 75.73 100.    72.78  79.51]
 [ -1.8   -1.72  -1.73 -40.95]
 [  0.     0.     0.     0.  ]
 [ -0.1   -0.1  -10.    27.1 ]
 [  0.     0.     0.     0.  ]]

Optimal path from start to goal:
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 3), (2, 3), (3, 3)]
